version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/Zurich
    open-pull-requests-limit: 0
    allow:
      - dependency-type: production
    labels:
      - dependencies
      - security
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      production-security-dependencies:
        applies-to: security-updates
        dependency-type: production
        patterns:
          - "*"
