packages/core:
  - changed-files:
      - any-glob-to-any-file:
          - packages/arcscord/*
          - packages/arcscord/**/*
packages/better-error:
  - changed-files:
      - any-glob-to-any-file:
          - packages/better_error/*
          - packages/better_error/**/*
packages/error:
  - changed-files:
      - any-glob-to-any-file:
          - packages/error/*
          - packages/error/**/*
packages/middleware:
  - changed-files:
      - any-glob-to-any-file:
          - packages/middleware/*
          - packages/middleware/**/*
packages/create-arcscord-bot:
  - changed-files:
      - any-glob-to-any-file:
          - packages/create-arcscord-bot/*
          - packages/create-arcscord-bot/**/*
