minimumReleaseAgeExclude:
  - "@types/node@26.0.0"
shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - detect-port@1.6.1
  - semver@6.3.1

packages:
  - "packages/*"
  - "test/*"
  - website

overrides:
  ansi-regex: ^5.0.1
  minimist: ^1.2.8

onlyBuiltDependencies:
  - "@prisma/engines"
  - better-sqlite3
  - prisma
peerDependencyRules:
  allowedVersions:
    tsconfck>typescript: "6"

allowBuilds:
  core-js: false
  esbuild: true
  sharp: true
