name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Linting:
    name: Linting NodeJS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v6
      - name: Add problem matchers
        run: echo "::add-matcher::.github/problemMatchers/eslint.json"
      - name: Use Node.js v24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run ESLint
        run: pnpm lint --fix=false

  Building:
    name: Build & Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v6
      - name: Add problem matchers
        run: echo "::add-matcher::.github/problemMatchers/tsc.json"
      - name: Use Node.js v24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - name: Clean pnpm cache
        run: pnpm store prune
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build code
        run: pnpm build
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        timeout-minutes: 15
      - name: Typecheck code
        run: pnpm typecheck
        timeout-minutes: 10

  UnitTesting:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v6
      - name: Use Node.js v24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run unit tests
        run: pnpm test
